### ISSUE TITLE
It requires dependency hosted in private Github Package Registry jcmtallon/ts-allies

### ISSUE THREAD

**Issue by julian-alarcon** [jcmtallon/garage_sale#3]
After doing the first `npm install` it's throwing an error related with authentication to the GitHub Package Registry.

The artifact that it's looking for it's not available to the public: https://github.com/jcmtallon/ts-allies

https://github.com/jcmtallon/garage_sale/blob/main/package.json#L12
https://github.com/jcmtallon/garage_sale/blob/main/.npmrc#L1

```sh
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN old lockfile HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="GitHub Package Registry"
npm WARN old lockfile     at /snap/node/6488/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:78:17
npm WARN old lockfile     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm WARN old lockfile     at async RegistryFetcher.packument (/snap/node/6488/lib/node_modules/npm/node_modules/pacote/lib/registry.js:92:19)
npm WARN old lockfile     at async RegistryFetcher.manifest (/snap/node/6488/lib/node_modules/npm/node_modules/pacote/lib/registry.js:124:23)
npm WARN old lockfile     at async Array.<anonymous> (/snap/node/6488/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:784:9)
npm WARN old lockfile  Could not fetch metadata for @jcmtallon/ts-allies@0.0.1 HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="GitHub Package Registry"
npm WARN old lockfile     at /snap/node/6488/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:78:17
npm WARN old lockfile     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm WARN old lockfile     at async RegistryFetcher.packument (/snap/node/6488/lib/node_modules/npm/node_modules/pacote/lib/registry.js:92:19)
npm WARN old lockfile     at async RegistryFetcher.manifest (/snap/node/6488/lib/node_modules/npm/node_modules/pacote/lib/registry.js:124:23)
npm WARN old lockfile     at async Array.<anonymous> (/snap/node/6488/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:784:9) {
npm WARN old lockfile   headers: [Object: null prototype] {
npm WARN old lockfile     'access-control-allow-methods': [ 'GET, HEAD, OPTIONS' ],
npm WARN old lockfile     'access-control-allow-origin': [ '*' ],
npm WARN old lockfile     'content-length': [ '0' ],
npm WARN old lockfile     'content-security-policy': [ "default-src 'none';" ],
npm WARN old lockfile     date: [ 'Tue, 12 Jul 2022 14:27:12 GMT' ],
npm WARN old lockfile     server: [ 'GitHub Registry' ],
npm WARN old lockfile     'strict-transport-security': [ 'max-age=31536000;' ],
npm WARN old lockfile     'www-authenticate': [ 'Basic realm="GitHub Package Registry"' ],
npm WARN old lockfile     'x-content-type-options': [ 'nosniff' ],
npm WARN old lockfile     'x-frame-options': [ 'DENY' ],
npm WARN old lockfile     'x-xss-protection': [ '1; mode=block' ],
npm WARN old lockfile     'x-github-request-id': [ '8236:82F2:84496:256268:62CD84C0' ],
npm WARN old lockfile     'x-fetch-attempts': [ '1' ],
npm WARN old lockfile     'x-local-cache-status': [ 'skip' ]
npm WARN old lockfile   },
npm WARN old lockfile   statusCode: 401,
npm WARN old lockfile   code: 'E401',
npm WARN old lockfile   method: 'GET',
npm WARN old lockfile   uri: 'https://npm.pkg.github.com/@jcmtallon%2fts-allies',
npm WARN old lockfile   body: <Buffer >,
npm WARN old lockfile   pkgid: '@jcmtallon/ts-allies@0.0.1'
npm WARN old lockfile }
npm WARN deprecated core-js-pure@3.15.2: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jalarcon/.npm/_logs/2022-07-12T14_27_11_278Z-debug-0.log
```

**Comment by myworldbox** [comment]
Therefore this app is not usable

**Comment by julian-alarcon** [comment]
I'm using an alternative and added some features: https://github.com/julian-alarcon/simple-garage-sale
